### PR TITLE
goodbye

### PR DESCRIPTION
**Pull request by cmelone**
cc: @brandonlieu2001 @girishbarca @noah-schechter

### CODE REVIEW

**Comment by noah-schechter** [comment]
This made me more sad than it had any right to. Will merge next Thursday after we've posted the catering menu.

**Comment by noah-schechter** [comment]
Also I don't know if you previewed the change but wow—I need to set a minimum height for the background image

**Comment by brandonlieu2001** [comment]
jesus fuck 😭😭😭🤽🏻‍♀️

**Comment by girishbarca** [comment]
LGTM!

**Pull request merged**
